import type { PRState, PullRequestFacts, WorkspaceSummary } from "../types/workspace";
import type { SessionPRSummary } from "../hooks/useSessionScmSummary";

const now = new Date().toISOString();
const minutesAgo = (minutes: number) => new Date(Date.now() - minutes * 60 * 1000).toISOString();
const hoursAgo = (hours: number) => new Date(Date.now() - hours * 60 * 60 * 1000).toISOString();

const demoPr = (
	number: number,
	state: PRState,
	ci: PullRequestFacts["ci"] = "passing",
	review: PullRequestFacts["review"] = "none",
	mergeability: PullRequestFacts["mergeability"] = "mergeable",
): PullRequestFacts => ({
	url: `https://github.com/acme-inc/ao-demo/pull/${number}`,
	number,
	state,
	ci,
	review,
	mergeability,
	reviewComments: review === "changes_requested",
	updatedAt: now,
});

export const mockWorkspaces: WorkspaceSummary[] = [
	{
		id: "ao-demo",
		name: "ao-demo",
		path: "/demo/ao-demo",
		type: "main",
		orchestratorAgent: "codex",
		accentColor: "#6ee7b7",
		sessions: [
			{
				id: "ao-demo-orchestrator",
				terminalHandleId: "ao-demo-orchestrator/terminal_0",
				workspaceId: "ao-demo",
				workspaceName: "ao-demo",
				title: "Project orchestrator",
				provider: "codex",
				kind: "orchestrator",
				branch: "main",
				status: "working",
				createdAt: hoursAgo(6),
				updatedAt: minutesAgo(3),
				activity: { state: "active", lastActivityAt: minutesAgo(3) },
				prs: [],
			},
			{
				id: "demo-working",
				terminalHandleId: "demo-working/terminal_0",
				workspaceId: "ao-demo",
				workspaceName: "ao-demo",
				title: "Build screenshot-ready dashboard data",
				provider: "codex",
				branch: "demo/dashboard-screenshot",
				status: "working",
				displayStatus: "working",
				createdAt: hoursAgo(3),
				updatedAt: minutesAgo(2),
				activity: { state: "active", lastActivityAt: minutesAgo(2) },
				changedFiles: [
					{ path: "frontend/src/renderer/lib/mock-data.ts", additions: 156, deletions: 22 },
					{ path: "docs/readme.md", additions: 18, deletions: 4 },
				],
				commitMessage: "prepare readme screenshot data",
				prs: [],
			},
			{
				id: "demo-needs-input",
				terminalHandleId: "demo-needs-input/terminal_0",
				workspaceId: "ao-demo",
				workspaceName: "ao-demo",
				title: "Resolve reviewer feedback on terminal polish",
				provider: "claude-code",
				branch: "demo/terminal-polish",
				status: "changes_requested",
				displayStatus: "needs_you",
				createdAt: hoursAgo(5),
				updatedAt: minutesAgo(18),
				activity: { state: "waiting_input", lastActivityAt: minutesAgo(18) },
				changedFiles: [
					{ path: "frontend/src/renderer/components/TerminalPane.tsx", additions: 41, deletions: 9 },
					{ path: "frontend/src/renderer/styles.css", additions: 27, deletions: 3 },
				],
				commitMessage: "polish terminal screenshots",
				prs: [demoPr(318, "open", "passing", "changes_requested")],
			},
			{
				id: "demo-review-stack",
				terminalHandleId: "demo-review-stack/terminal_0",
				workspaceId: "ao-demo",
				workspaceName: "ao-demo",
				title: "Review stacked browser preview flow",
				provider: "codex",
				branch: "demo/browser-preview-stack",
				status: "review_pending",
				displayStatus: "needs_you",
				createdAt: hoursAgo(7),
				updatedAt: minutesAgo(7),
				activity: { state: "idle", lastActivityAt: minutesAgo(7) },
				previewUrl: "http://localhost:5173",
				previewRevision: 4,
				changedFiles: [
					{ path: "frontend/src/renderer/components/BrowserPanel.tsx", additions: 52, deletions: 11 },
					{ path: "frontend/src/renderer/hooks/useBrowserView.ts", additions: 33, deletions: 6 },
					{ path: "docs/assets/readme/browser-preview.png", additions: 1, deletions: 0 },
				],
				commitMessage: "wire readme browser preview",
				prs: [
					demoPr(319, "open", "passing", "none"),
					demoPr(320, "open", "pending", "none", "unknown"),
					demoPr(321, "draft", "pending", "none", "unknown"),
				],
			},
			{
				id: "demo-in-review",
				terminalHandleId: "demo-in-review/terminal_0",
				workspaceId: "ao-demo",
				workspaceName: "ao-demo",
				title: "Wait for CI on project settings copy",
				provider: "opencode",
				branch: "demo/project-settings-copy",
				status: "review_pending",
				displayStatus: "unknown",
				createdAt: hoursAgo(4),
				updatedAt: minutesAgo(31),
				activity: { state: "idle", lastActivityAt: minutesAgo(31) },
				prs: [demoPr(322, "open", "pending", "none", "unknown")],
			},
			{
				id: "demo-ready",
				terminalHandleId: "demo-ready/terminal_0",
				workspaceId: "ao-demo",
				workspaceName: "ao-demo",
				title: "Merge README screenshot asset update",
				provider: "codex",
				branch: "demo/readme-assets",
				status: "mergeable",
				displayStatus: "mergeable",
				createdAt: hoursAgo(9),
				updatedAt: minutesAgo(5),
				activity: { state: "idle", lastActivityAt: minutesAgo(5) },
				changedFiles: [
					{ path: "docs/assets/readme/dashboard.png", additions: 1, deletions: 0 },
					{ path: "docs/assets/readme/session-terminal.png", additions: 1, deletions: 0 },
				],
				prs: [demoPr(323, "open", "passing", "approved")],
			},
			{
				id: "demo-ci-failed",
				terminalHandleId: "demo-ci-failed/terminal_0",
				workspaceId: "ao-demo",
				workspaceName: "ao-demo",
				title: "Fix flaky NewTaskDialog smoke test",
				provider: "codex",
				branch: "demo/new-task-flake",
				status: "ci_failed",
				displayStatus: "needs_you",
				createdAt: hoursAgo(8),
				updatedAt: minutesAgo(46),
				activity: { state: "idle", lastActivityAt: minutesAgo(46) },
				prs: [demoPr(324, "open", "failing", "none")],
			},
		],
	},
	{
		id: "pr-kanban-lab",
		name: "pr-kanban-lab",
		path: "/demo/pr-kanban-lab",
		type: "main",
		orchestratorAgent: "codex",
		accentColor: "#a78bfa",
		sessions: [
			{
				id: "pr-kanban-orchestrator",
				terminalHandleId: "pr-kanban-orchestrator/terminal_0",
				workspaceId: "pr-kanban-lab",
				workspaceName: "pr-kanban-lab",
				title: "PR board design orchestrator",
				provider: "codex",
				kind: "orchestrator",
				branch: "main",
				status: "working",
				createdAt: hoursAgo(10),
				updatedAt: minutesAgo(4),
				activity: { state: "active", lastActivityAt: minutesAgo(4) },
				prs: [],
			},
			{
				id: "pr-kanban-working",
				terminalHandleId: "pr-kanban-working/terminal_0",
				workspaceId: "pr-kanban-lab",
				workspaceName: "pr-kanban-lab",
				title: "Build compact PR card shell",
				provider: "codex",
				branch: "ui/pr-card-shell",
				status: "working",
				displayStatus: "working",
				createdAt: hoursAgo(2),
				updatedAt: minutesAgo(6),
				activity: { state: "active", lastActivityAt: minutesAgo(6) },
				changedFiles: [
					{ path: "frontend/src/renderer/components/PRCard.tsx", additions: 92, deletions: 18 },
					{ path: "frontend/src/renderer/styles.css", additions: 44, deletions: 6 },
				],
				commitMessage: "shape compact pull request cards",
				prs: [demoPr(615, "draft", "pending", "review_required", "unknown")],
			},
			{
				id: "pr-kanban-stack",
				terminalHandleId: "pr-kanban-stack/terminal_0",
				workspaceId: "pr-kanban-lab",
				workspaceName: "pr-kanban-lab",
				title: "Split settings redesign into stacked PRs",
				provider: "claude-code",
				branch: "ui/settings-stack",
				status: "review_pending",
				displayStatus: "unknown",
				createdAt: hoursAgo(7),
				updatedAt: minutesAgo(16),
				activity: { state: "idle", lastActivityAt: minutesAgo(16) },
				changedFiles: [
					{ path: "frontend/src/renderer/components/ProjectSettingsForm.tsx", additions: 118, deletions: 52 },
					{ path: "frontend/src/renderer/components/GlobalSettingsForm.tsx", additions: 63, deletions: 28 },
					{ path: "frontend/src/renderer/lib/settings-schema.ts", additions: 41, deletions: 0 },
				],
				commitMessage: "split settings surface into reviewable stack",
				prs: [
					demoPr(601, "draft", "pending", "review_required", "unknown"),
					demoPr(602, "open", "pending", "review_required", "unknown"),
					demoPr(603, "open", "passing", "review_required", "mergeable"),
					demoPr(604, "merged", "passing", "approved", "mergeable"),
				],
			},
			{
				id: "pr-kanban-review",
				terminalHandleId: "pr-kanban-review/terminal_0",
				workspaceId: "pr-kanban-lab",
				workspaceName: "pr-kanban-lab",
				title: "Address reviewer notes on command palette",
				provider: "opencode",
				branch: "ui/palette-review-fixes",
				status: "changes_requested",
				displayStatus: "needs_you",
				createdAt: hoursAgo(5),
				updatedAt: minutesAgo(22),
				activity: { state: "waiting_input", lastActivityAt: minutesAgo(22) },
				changedFiles: [
					{ path: "frontend/src/renderer/components/CommandPalette.tsx", additions: 36, deletions: 14 },
					{ path: "frontend/src/renderer/components/CommandPalette.test.tsx", additions: 29, deletions: 2 },
				],
				commitMessage: "respond to palette accessibility review",
				prs: [demoPr(612, "open", "passing", "changes_requested", "blocked")],
			},
			{
				id: "pr-kanban-ci",
				terminalHandleId: "pr-kanban-ci/terminal_0",
				workspaceId: "pr-kanban-lab",
				workspaceName: "pr-kanban-lab",
				title: "Fix flaky onboarding smoke test",
				provider: "codex",
				branch: "test/onboarding-smoke-flake",
				status: "ci_failed",
				displayStatus: "needs_you",
				createdAt: hoursAgo(4),
				updatedAt: minutesAgo(35),
				activity: { state: "idle", lastActivityAt: minutesAgo(35) },
				changedFiles: [
					{ path: "frontend/src/renderer/__tests__/onboarding-smoke.test.tsx", additions: 54, deletions: 21 },
					{ path: "frontend/src/renderer/components/NewTaskDialog.tsx", additions: 17, deletions: 5 },
				],
				commitMessage: "stabilize onboarding smoke flow",
				prs: [demoPr(611, "open", "failing", "none", "unstable")],
			},
			{
				id: "pr-kanban-conflict",
				terminalHandleId: "pr-kanban-conflict/terminal_0",
				workspaceId: "pr-kanban-lab",
				workspaceName: "pr-kanban-lab",
				title: "Resolve sidebar navigation conflict",
				provider: "aider",
				branch: "fix/sidebar-route-conflict",
				status: "needs_input",
				displayStatus: "needs_you",
				createdAt: hoursAgo(9),
				updatedAt: minutesAgo(41),
				activity: { state: "waiting_input", lastActivityAt: minutesAgo(41) },
				changedFiles: [
					{ path: "frontend/src/renderer/components/Sidebar.tsx", additions: 23, deletions: 31 },
					{ path: "frontend/src/renderer/routeTree.gen.ts", additions: 8, deletions: 8 },
				],
				commitMessage: "resolve sidebar route conflict",
				prs: [demoPr(613, "open", "passing", "approved", "conflicting")],
			},
			{
				id: "pr-kanban-ready",
				terminalHandleId: "pr-kanban-ready/terminal_0",
				workspaceId: "pr-kanban-lab",
				workspaceName: "pr-kanban-lab",
				title: "Ship notification center polish",
				provider: "codex",
				branch: "ui/notification-polish",
				status: "mergeable",
				displayStatus: "mergeable",
				createdAt: hoursAgo(11),
				updatedAt: minutesAgo(9),
				activity: { state: "idle", lastActivityAt: minutesAgo(9) },
				changedFiles: [
					{ path: "frontend/src/renderer/components/NotificationCenter.tsx", additions: 47, deletions: 19 },
					{ path: "frontend/src/renderer/components/ShellTopbar.tsx", additions: 12, deletions: 4 },
				],
				commitMessage: "polish notification center affordances",
				prs: [demoPr(614, "open", "passing", "approved", "mergeable")],
			},
		],
	},
	{
		id: "docs-site",
		name: "docs-site",
		path: "/demo/docs-site",
		type: "main",
		orchestratorAgent: "claude-code",
		accentColor: "#93c5fd",
		sessions: [
			{
				id: "docs-installation",
				terminalHandleId: "docs-installation/terminal_0",
				workspaceId: "docs-site",
				workspaceName: "docs-site",
				title: "Tighten installation guide",
				provider: "claude-code",
				branch: "demo/install-docs",
				status: "working",
				createdAt: hoursAgo(2),
				updatedAt: minutesAgo(13),
				activity: { state: "active", lastActivityAt: minutesAgo(13) },
				prs: [],
			},
			{
				id: "docs-ready",
				terminalHandleId: "docs-ready/terminal_0",
				workspaceId: "docs-site",
				workspaceName: "docs-site",
				title: "Publish troubleshooting section",
				provider: "codex",
				branch: "demo/troubleshooting",
				status: "approved",
				createdAt: hoursAgo(12),
				updatedAt: minutesAgo(22),
				activity: { state: "idle", lastActivityAt: minutesAgo(22) },
				prs: [demoPr(411, "open", "passing", "approved")],
			},
		],
	},
];

const prSummary = (sessionId: string, number: number, overrides: Partial<SessionPRSummary> = {}): SessionPRSummary => {
	const session = mockWorkspaces.flatMap((workspace) => workspace.sessions).find((item) => item.id === sessionId);
	const facts = session?.prs.find((item) => item.number === number);
	const url = facts?.url ?? `https://github.com/me/${session?.workspaceName ?? "preview"}/pull/${number}`;
	return {
		url,
		htmlUrl: url,
		number,
		title: session?.title ?? `PR #${number}`,
		state: facts?.state ?? "open",
		provider: "github",
		repo: `me/${session?.workspaceName ?? "preview"}`,
		author: "preview-agent",
		sourceBranch: session?.branch ?? "",
		targetBranch: "main",
		headSha: `preview-${number}`,
		additions: 42,
		deletions: 8,
		changedFiles: 3,
		ci: {
			state: facts?.ci === "failing" ? "failing" : facts?.ci === "pending" ? "pending" : "passing",
			failingChecks: [],
		},
		review: {
			decision:
				facts?.review === "changes_requested"
					? "changes_requested"
					: facts?.review === "approved"
						? "approved"
						: "none",
			hasUnresolvedHumanComments: facts?.reviewComments ?? false,
			unresolvedBy: [],
		},
		mergeability: {
			state:
				facts?.mergeability === "conflicting"
					? "conflicting"
					: facts?.mergeability === "blocked"
						? "blocked"
						: facts?.mergeability === "unstable"
							? "unstable"
							: facts?.mergeability === "unknown"
								? "unknown"
								: "mergeable",
			reasons: [],
			prUrl: url,
			conflictFiles: [],
		},
		updatedAt: facts?.updatedAt ?? now,
		observedAt: facts?.updatedAt ?? now,
		ciObservedAt: facts?.updatedAt ?? now,
		reviewObservedAt: facts?.updatedAt ?? now,
		...overrides,
	};
};

export const mockSessionScmSummaries: Record<string, SessionPRSummary[]> = {
	"pr-kanban-working": [
		prSummary("pr-kanban-working", 615, {
			title: "Build compact PR card shell",
			state: "draft",
			author: "codex-ui",
			sourceBranch: "ui/pr-card-shell",
			headSha: "b7f12c9",
			changedFiles: 2,
			additions: 92,
			deletions: 18,
			ci: { state: "pending", failingChecks: [] },
			review: { decision: "review_required", hasUnresolvedHumanComments: false, unresolvedBy: [] },
			mergeability: {
				state: "unknown",
				reasons: ["draft", "ci_pending"],
				prUrl: "https://github.com/me/pr-kanban-lab/pull/615",
				conflictFiles: [],
			},
		}),
	],
	"pr-kanban-stack": [
		prSummary("pr-kanban-stack", 601, {
			title: "Settings stack 1/4: shared form primitives",
			state: "draft",
			author: "claude-ui",
			sourceBranch: "ui/settings-stack-forms",
			headSha: "601a7fd",
			changedFiles: 4,
			additions: 118,
			deletions: 52,
			ci: { state: "pending", failingChecks: [] },
			review: { decision: "review_required", hasUnresolvedHumanComments: false, unresolvedBy: [] },
			mergeability: {
				state: "unknown",
				reasons: ["draft", "stack_base_pending"],
				prUrl: "https://github.com/me/pr-kanban-lab/pull/601",
				conflictFiles: [],
			},
		}),
		prSummary("pr-kanban-stack", 602, {
			title: "Settings stack 2/4: project settings layout",
			state: "open",
			author: "claude-ui",
			sourceBranch: "ui/project-settings-layout",
			headSha: "602bf41",
			changedFiles: 3,
			additions: 96,
			deletions: 27,
			ci: { state: "pending", failingChecks: [] },
			review: { decision: "review_required", hasUnresolvedHumanComments: false, unresolvedBy: [] },
			mergeability: {
				state: "unknown",
				reasons: ["ci_pending"],
				prUrl: "https://github.com/me/pr-kanban-lab/pull/602",
				conflictFiles: [],
			},
		}),
		prSummary("pr-kanban-stack", 603, {
			title: "Settings stack 3/4: global preferences copy",
			state: "open",
			author: "claude-ui",
			sourceBranch: "ui/global-settings-copy",
			headSha: "603dd89",
			changedFiles: 5,
			additions: 84,
			deletions: 36,
			ci: { state: "passing", failingChecks: [] },
			review: { decision: "review_required", hasUnresolvedHumanComments: false, unresolvedBy: [] },
			mergeability: {
				state: "mergeable",
				reasons: ["review_required"],
				prUrl: "https://github.com/me/pr-kanban-lab/pull/603",
				conflictFiles: [],
			},
		}),
		prSummary("pr-kanban-stack", 604, {
			title: "Settings stack 4/4: remove legacy panel chrome",
			state: "merged",
			author: "claude-ui",
			sourceBranch: "ui/remove-settings-chrome",
			headSha: "604f31a",
			changedFiles: 2,
			additions: 19,
			deletions: 74,
			ci: { state: "passing", failingChecks: [] },
			review: { decision: "approved", hasUnresolvedHumanComments: false, unresolvedBy: [] },
			mergeability: {
				state: "mergeable",
				reasons: [],
				prUrl: "https://github.com/me/pr-kanban-lab/pull/604",
				conflictFiles: [],
			},
		}),
	],
	"pr-kanban-review": [
		prSummary("pr-kanban-review", 612, {
			title: "Address reviewer notes on command palette",
			author: "open-ui",
			sourceBranch: "ui/palette-review-fixes",
			headSha: "612aa90",
			changedFiles: 2,
			additions: 36,
			deletions: 14,
			ci: { state: "passing", failingChecks: [] },
			review: {
				decision: "changes_requested",
				hasUnresolvedHumanComments: true,
				unresolvedBy: [
					{
						reviewerId: "maya",
						count: 3,
						reviewUrl: "https://github.com/me/pr-kanban-lab/pull/612#pullrequestreview-9001",
						links: [
							{
								url: "https://github.com/me/pr-kanban-lab/pull/612#discussion_r9001",
								file: "frontend/src/renderer/components/CommandPalette.tsx",
								line: 88,
							},
							{
								url: "https://github.com/me/pr-kanban-lab/pull/612#discussion_r9002",
								file: "frontend/src/renderer/components/CommandPalette.tsx",
								line: 134,
							},
						],
					},
				],
			},
			mergeability: {
				state: "blocked",
				reasons: ["changes_requested"],
				prUrl: "https://github.com/me/pr-kanban-lab/pull/612",
				conflictFiles: [],
			},
		}),
	],
	"pr-kanban-ci": [
		prSummary("pr-kanban-ci", 611, {
			title: "Fix flaky onboarding smoke test",
			author: "codex-test",
			sourceBranch: "test/onboarding-smoke-flake",
			headSha: "611c0de",
			changedFiles: 2,
			additions: 54,
			deletions: 21,
			ci: {
				state: "failing",
				failingChecks: [
					{
						name: "Playwright / onboarding smoke",
						status: "failed",
						conclusion: "failure",
						url: "https://github.com/me/pr-kanban-lab/actions/runs/611001/job/1",
					},
					{
						name: "Chromium / NewTaskDialog",
						status: "failed",
						conclusion: "timeout",
						url: "https://github.com/me/pr-kanban-lab/actions/runs/611001/job/2",
					},
					{
						name: "api contract drift",
						status: "failed",
						conclusion: "failure",
						url: "https://github.com/me/pr-kanban-lab/actions/runs/611001/job/3",
					},
				],
			},
			review: { decision: "none", hasUnresolvedHumanComments: false, unresolvedBy: [] },
			mergeability: {
				state: "unstable",
				reasons: ["ci_failing"],
				prUrl: "https://github.com/me/pr-kanban-lab/pull/611",
				conflictFiles: [],
			},
		}),
	],
	"pr-kanban-conflict": [
		prSummary("pr-kanban-conflict", 613, {
			title: "Resolve sidebar navigation conflict",
			author: "aider-ui",
			sourceBranch: "fix/sidebar-route-conflict",
			headSha: "613ff09",
			changedFiles: 2,
			additions: 23,
			deletions: 31,
			ci: { state: "passing", failingChecks: [] },
			review: { decision: "approved", hasUnresolvedHumanComments: false, unresolvedBy: [] },
			mergeability: {
				state: "conflicting",
				reasons: ["conflicts"],
				prUrl: "https://github.com/me/pr-kanban-lab/pull/613",
				conflictFiles: [
					{
						path: "frontend/src/renderer/components/Sidebar.tsx",
						url: "https://github.com/me/pr-kanban-lab/pull/613/conflicts#sidebar",
					},
					{
						path: "frontend/src/renderer/routeTree.gen.ts",
						url: "https://github.com/me/pr-kanban-lab/pull/613/conflicts#routes",
					},
				],
			},
		}),
	],
	"pr-kanban-ready": [
		prSummary("pr-kanban-ready", 614, {
			title: "Ship notification center polish",
			author: "codex-ui",
			sourceBranch: "ui/notification-polish",
			headSha: "614beef",
			changedFiles: 2,
			additions: 47,
			deletions: 19,
			ci: { state: "passing", failingChecks: [] },
			review: { decision: "approved", hasUnresolvedHumanComments: false, unresolvedBy: [] },
			mergeability: {
				state: "mergeable",
				reasons: [],
				prUrl: "https://github.com/me/pr-kanban-lab/pull/614",
				conflictFiles: [],
			},
		}),
	],
	"fix-auth-timeouts": [
		prSummary("fix-auth-timeouts", 184, {
			changedFiles: 5,
			additions: 91,
			deletions: 17,
			ci: {
				state: "failing",
				failingChecks: [
					{
						name: "backend / go test ./...",
						status: "failed",
						conclusion: "failure",
						url: "https://github.com/me/api-gateway/actions/runs/184001/job/1",
					},
					{
						name: "lint / golangci",
						status: "failed",
						conclusion: "failure",
						url: "https://github.com/me/api-gateway/actions/runs/184001/job/2",
					},
					{
						name: "api contract drift",
						status: "failed",
						conclusion: "failure",
						url: "https://github.com/me/api-gateway/actions/runs/184001/job/3",
					},
					{
						name: "frontend typecheck",
						status: "failed",
						conclusion: "",
						url: "https://github.com/me/api-gateway/actions/runs/184001/job/4",
					},
				],
			},
		}),
	],
	"texture-leak": [
		prSummary("texture-leak", 51, {
			changedFiles: 4,
			additions: 74,
			deletions: 22,
			ci: {
				state: "failing",
				failingChecks: [
					{
						name: "render tests",
						status: "failed",
						conclusion: "failure",
						url: "https://github.com/me/webgl-preview/actions/runs/51001/job/1",
					},
					{
						name: "visual regression",
						status: "failed",
						conclusion: "failure",
						url: "https://github.com/me/webgl-preview/actions/runs/51001/job/2",
					},
				],
			},
			mergeability: {
				state: "conflicting",
				reasons: ["conflicts"],
				prUrl: "https://github.com/me/webgl-preview/pull/51",
				conflictFiles: [
					{
						path: "src/render/texture-cache.ts",
						url: "https://github.com/me/webgl-preview/pull/51/conflicts#src-render-texture-cache-ts",
					},
					{
						path: "src/render/webgl-context.ts",
						url: "https://github.com/me/webgl-preview/pull/51/conflicts#src-render-webgl-context-ts",
					},
				],
			},
		}),
	],
	"review-camera-pan": [
		prSummary("review-camera-pan", 52, {
			changedFiles: 6,
			additions: 128,
			deletions: 31,
			review: {
				decision: "review_required",
				hasUnresolvedHumanComments: false,
				unresolvedBy: [],
			},
		}),
	],
	"input-pointer-lock": [
		prSummary("input-pointer-lock", 56, {
			changedFiles: 3,
			additions: 48,
			deletions: 14,
			review: {
				decision: "changes_requested",
				hasUnresolvedHumanComments: true,
				unresolvedBy: [
					{
						reviewerId: "maya",
						count: 3,
						reviewUrl: "https://github.com/me/webgl-preview/pull/56#pullrequestreview-1001",
						links: [
							{
								url: "https://github.com/me/webgl-preview/pull/56#discussion_r1001",
								file: "src/input/pointer-lock.ts",
								line: 88,
							},
							{
								url: "https://github.com/me/webgl-preview/pull/56#discussion_r1002",
								file: "src/input/keyboard.ts",
								line: 41,
							},
						],
					},
					{
						reviewerId: "copilot",
						count: 1,
						isBot: true,
						reviewUrl: "https://github.com/me/webgl-preview/pull/56#pullrequestreview-1002",
						links: [],
					},
				],
			},
		}),
	],
	"invoice-export": [
		prSummary("invoice-export", 117, {
			changedFiles: 8,
			additions: 212,
			deletions: 36,
			mergeability: {
				state: "blocked",
				reasons: ["behind_base", "review_required", "blocked_by_provider", "ci_failing"],
				prUrl: "https://github.com/me/billing-portal/pull/117",
				conflictFiles: [],
			},
		}),
	],
};
